polls/urls.py
from django.urls import path
from .views import IndexView

from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('submit_question/', views.submit_question, name='submit_question'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import JSONField  # If using Django version < 3.1

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    response_text = models.TextField()
    pub_date = models.DateTimeField()
    actions = models.JSONField(default=list, blank=True)
    emotions = models.JSONField(default=list, blank=True)
    people = models.JSONField(default=list, blank=True)

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.utils import timezone
from .models import Question
from .api import process_response_text
from django.urls import reverse
action_list = []
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")

def submit_question(request):
    if request.method == "POST":
        question_text = request.POST.get('question_text', '')
        response_text = request.POST.get('response_text', '')

        if question_text and response_text:
            actions, people, emotions = process_response_text(response_text)  # Adjusted to unpack the tuple
            question = Question.objects.create(
                question_text=question_text,
                response_text=response_text,
                actions=actions,  # Assuming your model has these fields now
                people=people,
                emotions=emotions,
                pub_date=timezone.now()
            )

            return redirect(f"{reverse('polls:index')}?latest_id={question.id}")
        


from collections import defaultdict

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    latest_id = request.GET.get('latest_id', None)

    context = {
        'latest_question_list': latest_question_list,
        'latest_id': latest_id
    }
    return render(request, 'polls/index.html', context)

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Record a Dream</title>
    <link rel="stylesheet" href="{% static 'polls/stylesheet.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/ycn5xxv.css">
</head>

<body>

    <div class="modal-overlay" id="modalOverlay" style="display: none;">
        <div id="modal" class="modal">
        <form id="dreamForm" method="post" action="{% url 'polls:submit_question' %}" autocomplete="off">
            {% csrf_token %}
            <h1>Record a dream</h1>
            <label for="question_text">Your name:</label>
            <input type="text" name="question_text" id="question_text" required><br>
            <label for="response_text">Your dream:</label>
            <textarea name="response_text" id="response_text" required rows="3" style="width: 100%;"></textarea><br>
            <button id="submit" type="submit">Submit</button>
        </form>
    </div>
    </div>

    <div class="fixedLayer">
        <div id="timeTravel">
        <label for="timeSlider">Time Travel</label>
        <input type="range" id="timeSlider" name="timeSlider" min="0" max="4" value="0">
        <div id="sliderValue">Today</div>
        </div>

        <button id="removeLines">Find Connections</button>
        <button id="openModal">Record a Dream</button>
        <div id="infoBox">Data set</div>
        <div id="questionCount">Dream Count: 0</div>
        <div id="nyClock">Loading current time...</div>
    </div>

    <div id="content">
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="response" data-entry-id="{{ question.id }}" data-creation-date="{{ question.pub_date|date:'Y-m-d H:i' }}">
                    <div 
                            class="question-text" data-entry-id="{{ question.id }}" data-response-text="{{ question.response_text }}">{{ question.question_text }}
                    </div>
    
                    <!-- Link question texts to their actions, now only referencing unique actions -->
                    <div class="actions">
                        {% for action in question.actions %}
                            <div class="action-item" data-entry-id="{{ question.id }}">{{ action }}</div>
                        {% endfor %}
                    </div>
    
                    <!-- Displaying Emotions as separate divs -->
                    <div class="emotions">
                        {% for emotion in question.emotions %}
                            <div class="emotion-item" data-entry-id="{{ question.id }}">{{ emotion }}</div>
                        {% endfor %}
                    </div>
    
                    <!-- Displaying People as separate divs -->
                    <div class="people">
                        {% for person in question.people %}
                            <div class="person-item" data-entry-id="{{ question.id }}">{{ person }}</div>
                        {% endfor %}
                    </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</div>

<svg class="svg-container"> 
</svg>

<script src="{% static 'polls/js/script.js' %}"> </script>
    
</body>